### ISSUE TITLE
Auto-tick 2FA "remember me" checkbox

### ISSUE THREAD

**Issue by violine1101** [mojira/mojira-plus#85]
Automatically tick the "remember me for 720 hour(s)" checkbox on the 2FA screen, since it's easy to miss it.

The HTML element ID is `#remember-me-user-enable`.

**Comment by osfanbuff63** [comment]
Duplicate of #78? might want to merge the other way though because this has more details?

**Comment by violine1101** [comment]
Yes, thanks. Should really do something about this then if I already created two issues about it.
